namespace ZCrew.Extensions.Tasks;

/// <summary>
///     Represents the method that will handle an event that has no event data.
/// </summary>
/// <param name="sender">The source of the event.</param>
/// <param name="eventArgs">An object that contains no event data.</param>
/// <param name="token">The token to monitor for cancellation requests.</param>
public delegate Task AsyncEventHandler(object sender, EventArgs eventArgs, CancellationToken token = default);

/// <summary>
///     Represents the method that will handle an event when the event provides data.
/// </summary>
/// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
/// <param name="sender">The source of the event.</param>
/// <param name="eventArgs">An object that contains the event data.</param>
/// <param name="token">The token to monitor for cancellation requests.</param>
public delegate Task AsyncEventHandler<in TEventArgs>(
    object sender,
    TEventArgs eventArgs,
    CancellationToken token = default
);
